root = "."
tmp_dir = "tmp"

[build]
  entrypoint = "./cmd/api/main.go"
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".git"]
  include_dir = ["cmd", "internal"]
  delay = 1000
  poll = true
  poll_interval = 2000

[log]
  time = true